# Generated by Django 5.0.2 on 2024-07-07 18:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_order_is_paid_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pub_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
